# Generated by Django 5.2 on 2025-05-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_created_at_alter_post_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="publication_attribute",
        ),
        migrations.AddField(
            model_name="post",
            name="publication",
            field=models.BooleanField(default=True),
        ),
    ]
