# Generated by Django 5.2 on 2025-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_publication_attribute"),
    ]

    operations = [

    ]
