# Generated by Django 5.2 on 2025-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("moderation", "На модерации"),
                    ("published", "Опубликовано"),
                    ("rejected", "Отклонено"),
                    ("archived", "В архиве"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
