# Generated by Django 5.2 on 2025-05-25 15:28

from django.db import migrations
from django.contrib.auth import get_user_model


def set_product_owners(apps, schema_editor):
    User = get_user_model()
    Product = apps.get_model('catalog', 'Product')

    # Находим первого суперпользователя
    superuser = User.objects.filter(is_superuser=True).first()
    if not superuser:
        # Если нет суперпользователя, создаем его
        superuser = User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='adminpass'
        )

    # Назначаем суперпользователя владельцем всех продуктов
    Product.objects.filter(owner__isnull=True).update(owner=superuser)


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0006_product_owner'),  # Укажите предыдущую миграцию
    ]

    operations = [
        migrations.RunPython(set_product_owners),
    ]