# Generated by Django 5.2 on 2025-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="машинка", max_length=100, unique=True),
        ),
    ]
