# Generated by Django 5.2 on 2025-05-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": [("delete_product", "Может удалять любой продукт")],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
