# Generated by Django 5.2 on 2025-05-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
